characters:
  - id: pfarrer_paul
    name: Pastor Paul
    folder: assets/characters/pfarrer_paul
    archetype: Priest
  - id: gina
    name: Gina
    folder: assets/characters/gina
    archetype: Overprotective mother
  - id: werner
    name: Werner
    folder: assets/characters/werner
    archetype: Cozy drinker
  - id: max
    name: Max
    folder: assets/characters/max
    archetype: Jack of all trades
  - id: eric
    name: Eric
    folder: assets/characters/eric
    archetype: Honest egoist
  - id: professor_herbert
    name: Professor Herbert
    folder: assets/characters/professor_herbert
    archetype: Explainer
  - id: berthold
    name: Berthold
    folder: assets/characters/berthold
    archetype: Angler
  - id: torsten
    name: Torsten
    folder: assets/characters/torsten
    archetype: Mail carrier
  - id: tina
    name: Tina
    folder: assets/characters/tina
    archetype: Garbage worker
  - id: heinrich
    name: Heinrich
    folder: assets/characters/heinrich
    archetype: Family man
  - id: sabrina
    name: Sabrina
    folder: assets/characters/sabrina
    archetype: Charmer
  - id: doktor_klara
    name: Doctor Klara
    folder: assets/characters/doktor_klara
    archetype: Doctor
  - id: buergermeister_bruno
    name: Mayor Bruno
    folder: assets/characters/buergermeister_bruno
    archetype: Overwhelmed leader
  - id: fitness_fiona
    name: Fitness Fiona
    folder: assets/characters/fitness_fiona
    archetype: Motivator
  - id: oma_gerda
    name: Grandma Gerda
    folder: assets/characters/oma_gerda
    archetype: Wise elder
  - id: hacker_hannes
    name: Hacker Hannes
    folder: assets/characters/hacker_hannes
    archetype: Conspiracy theorist
  - id: kuenstler_kurt
    name: Artist Kurt
    folder: assets/characters/kuenstler_kurt
    archetype: Misunderstood artist
